bpdm-gate:
  image:
    pullPolicy: Always
  fullnameOverride: bpdm-dev-gate-test-company
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 2Gi
  ingress:
    enabled: true
    hosts:
      - host: business-partners.dev.demo.catena-x.net
        paths:
          - path: "/companies/test-company"
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - business-partners.dev.demo.catena-x.net
  livenessProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/companies/test-company"
    bpdm:
      bpn:
        owner-bpn-l:
      tasks:
        creation:
          fromSharingMember:
            cron: '*/30 * * * * *'
            batchSize: 20
          fromPool:
            batchSize: 20
            cron: '*/30 * * * * *'
      client:
        orchestrator:
          base-url: "http://bpdm-dev-orchestrator/orchestrator"
          registration:
            client-id: sa-cl7-cx-7
        pool:
          base-url: "http://bpdm-dev-pool/pool"
          registration:
            client-id: sa-cl7-cx-7
      security:
        auth-server-url: https://centralidp.dev.demo.catena-x.net/auth
        realm: CX-Central
        client-id: Cl16-CX-BPDMGate
        permissions:
          readInputPartner: write_partner
          writeInputPartner: write_partner
          readOutputPartner: write_partner
          readInputChangelog: write_partner
          readOutputChangelog: write_partner
          readSharingState: write_partner
          writeSharingState: write_partner
          read_stats: write_partner
          uploadInputPartner: write_partner
    springdoc:
      swagger-ui:
        oauth:
          client-id: Cl2-CX-Portal
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/dev/pool/postgresql#password>
    bpdm:
      client:
        pool:
          registration:
            client-secret: <path:bpdm/data/dev/pool/admin-user#client-secret>
        orchestrator:
          registration:
            client-secret: <path:bpdm/data/dev/pool/admin-user#client-secret>

  postgres:
    enabled: false
    fullnameOverride: ""

bpdm-pool:
  image:
    pullPolicy: Always
  fullnameOverride: bpdm-dev-pool
  enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 2Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: business-partners.dev.demo.catena-x.net
        paths:
          - path: /pool
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - business-partners.dev.demo.catena-x.net
  livenessProbe:
    httpGet:
      path: "/pool/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/pool/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/pool/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/pool"
    bpdm:
      tasks:
        cron: "*/30 * * * * *"
        batchSize: 20
      client:
        orchestrator:
          base-url: "http://bpdm-dev-orchestrator/orchestrator"
          registration:
            client-id: sa-cl7-cx-7
      security:
        auth-server-url: https://centralidp.dev.demo.catena-x.net/auth
        realm: CX-Central
        client-id: Cl7-CX-BPDM
        permissions:
          readPartner: write_partner
          writePartner: write_partner
          readMemberPartner: write_partner
          readMetaData: write_partner
          writeMetaData: write_partner
          readChangelog: write_partner
          readMemberChangelog: write_partner
    springdoc:
      swagger-ui:
        oauth:
          client-id: Cl2-CX-Portal
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/dev/pool/postgresql#password>
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret: <path:bpdm/data/dev/pool/admin-user#client-secret>
  postgres:
    enabled: false
    fullnameOverride: ""

bpdm-orchestrator:
  image:
    pullPolicy: Always
  fullnameOverride: bpdm-dev-orchestrator
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 2Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: business-partners.dev.demo.catena-x.net
        paths:
          - path: /orchestrator
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - business-partners.dev.demo.catena-x.net
  livenessProbe:
    httpGet:
      path: "orchestrator/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "orchestrator/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "orchestrator/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/orchestrator"
    bpdm:
      security:
        auth-server-url: https://centralidp.dev.demo.catena-x.net/auth
        realm: CX-Central
        client-id: Cl7-CX-BPDM
        permissions:
          createTask: write_partner
          readTask: write_partner
          reservation:
            clean: write_partner
            cleanAndSync: write_partner
            poolSync: write_partner
          result:
            clean: write_partner
            cleanAndSync: write_partner
            poolSync: write_partner

bpdm-cleaning-service-dummy:
  image:
    pullPolicy: Always
  fullnameOverride: bpdm-dev-cleaning-service
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 2Gi
  applicationConfig:
    bpdm:
      client:
        orchestrator:
          base-url: "http://bpdm-dev-orchestrator/orchestrator"
          provider:
            issuer-uri: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central
          registration:
            client-id: sa-cl7-cx-7
      cleaningService:
        pollingCron: "*/30 * * * * *"
  applicationSecrets:
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret:  <path:bpdm/data/dev/pool/admin-user#client-secret>

postgres:
  fullnameOverride: ""
  auth:
    postgresPassword: <path:bpdm/data/dev/pool/postgresql#postgres-password>
    password: <path:bpdm/data/dev/pool/postgresql#password>

keycloak:
  enabled: true
  postgresql:
    enabled: true
    nameOverride: "keycloak-postgres"
    auth:
      postgresPassword: <path:bpdm/data/dev/keycloak#postgresql-password>
      username: bn_keycloak
      password: <path:bpdm/data/dev/keycloak#user-password>
      database: bitnami_keycloak
  auth:
    adminPassword: <path:bpdm/data/dev/pool/postgresql#password>
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "bpdm-keycloak.dev.demo.catena-x.net"
    servicePort: http
