image:
  tag: "main"

springProfiles:
  - auth
  - pool-auth

ingress:
  enabled: true
  hosts:
    - host: partners-gate.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - partners-gate.dev.demo.catena-x.net

applicationConfig:
  bpdm:
    pool:
      base-url: https://partners-pool.int.demo.catena-x.net/api/catena
    saas:
      host: https://api.cdq.com
      storage: 38d2277e20c730b4b8e8f182adcef7ca
      datasource: 621338451197b7667a5fbda4
    security:
      auth-server-url: https://centralidp.dev.demo.catena-x.net/auth
      realm: CX-Central
      client-id: Cl16-CX-BPDMGate
  spring:
    security:
      oauth2:
        client:
          registration:
            gate-client:
              # Client ID used for getting token different from own Client to validate tokens
              client-id: sa-cl16-cx-1
          provider:
            catena-keycloak-provider:
              issuer-uri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central

  springdoc:
    swagger-ui:
      oauth:
        client-id: Cl2-CX-Portal

applicationSecrets:
  spring:
    datasource:
      password: <path:bpdm/data/dev/pool/postgresql#password>
  bpdm:
    saas:
      api-key: <path:bpdm/data/dev/gate/cdq#api-key>
    security:
      credentials:
        secret: <path:bpdm/data/dev/gate/service-account#client-secret>

postgres:
  auth:
    postgresPassword: <path:bpdm/data/dev/pool/postgresql#postgres-password>
    password: <path:bpdm/data/dev/pool/postgresql#password>