image:
  tag: "main"

springProfiles:
  - auth
  - pool-auth

ingress:
  enabled: true
  hosts:
    - host: partners-gate.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - partners-gate.dev.demo.catena-x.net

applicationConfig:
  bpdm:
    pool:
      base-url: http://pool-bpdm-pool:8080/api/catena
    cdq:
      storage: 38d2277e20c730b4b8e8f182adcef7ca
      datasource: 621338451197b7667a5fbda4
    security:
      auth-server-url: https://centralidp.dev.demo.catena-x.net/auth
      realm: CX-Central
      client-id: Cl16-CX-BPDMGate
  spring:
    security:
      oauth2:
        client:
          registration:
            gate-client:
              # Client ID used for getting token different from own Client to validate tokens
              client-id: sa-cl16-cx-1

  springdoc:
    swagger-ui:
      oauth:
        client-id: Cl2-CX-Portal

applicationSecrets:
  bpdm:
    cdq:
      api-key: <path:bpdm/data/dev/gate/cdq#api-key>
    security:
      credentials:
        secret: <path:bpdm/data/dev/gate/service-account#client-secret>