bpdm-gate:
  fullnameOverride: bpdm-int-gate-test-company
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  ingress:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
      - host: business-partners.int.catena-x.net
        paths:
          - path: "/companies/test-company"
            pathType: Prefix
    tls:
      - secretName: tls-secret-bpdm-gate
        hosts:
          - business-partners.int.catena-x.net
  livenessProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/companies/test-company"
    bpdm:
      bpn:
        owner-bpn-l:
      tasks:
        creation:
          fromSharingMember:
            starts-as-ready: false
      client:
        pool:
          base-url: "http://bpdm-int-pool/pool"
          registration:
            client-id: <path:bpdm/data/int/bpdm/gates/portal/pool-client#client-id>
        orchestrator:
          base-url: "http://bpdm-int-orchestrator/orchestrator"
          registration:
            client-id: <path:bpdm/data/int/bpdm/gates/portal/orchestrator-client#client-id>
      security:
        auth-server-url: https://centralidp.int.catena-x.net/auth
        realm: CX-Central
        client-id: Cl16-CX-BPDMGate
    springdoc:
      swagger-ui:
        oauth:
          client-id: Cl2-CX-Portal
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/int/bpdm/postgresql#password>
    bpdm:
      client:
        pool:
          registration:
            client-secret: <path:bpdm/data/int/bpdm/gates/portal/pool-client#client-secret>
        orchestrator:
          registration:
            client-secret: <path:bpdm/data/int/bpdm/gates/portal/orchestrator-client#client-secret>

  postgres:
    enabled: false
    fullnameOverride: ""

bpdm-pool:
  fullnameOverride: bpdm-int-pool
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: business-partners.int.catena-x.net
        paths:
          - path: /pool
            pathType: Prefix
    tls:
      - secretName: tls-secret-bpdm-pool
        hosts:
          - business-partners.int.catena-x.net
  livenessProbe:
    httpGet:
      path: "/pool/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/pool/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/pool/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/pool"
    bpdm:
      client:
        orchestrator:
          base-url: "http://bpdm-int-orchestrator/orchestrator"
          registration:
            client-id: <path:bpdm/data/int/bpdm/pool/orchestrator-client#client-id>
      security:
        auth-server-url: https://centralidp.int.catena-x.net/auth
        realm: CX-Central
        client-id: Cl7-CX-BPDM
    springdoc:
      swagger-ui:
        oauth:
          client-id: Cl2-CX-Portal
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/int/bpdm/postgresql#password>
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret: <path:bpdm/data/int/bpdm/pool/orchestrator-client#client-secret>
  postgres:
    enabled: false
    fullnameOverride: ""

bpdm-orchestrator:
  fullnameOverride: bpdm-int-orchestrator
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: business-partners.int.catena-x.net
        paths:
          - path: /orchestrator
            pathType: Prefix
    tls:
      - secretName: tls-secret-bpdm-orchestrator
        hosts:
          - business-partners.int.catena-x.net
  livenessProbe:
    httpGet:
      path: "orchestrator/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "orchestrator/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "orchestrator/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/orchestrator"
    bpdm:
      security:
        auth-server-url: https://centralidp.int.catena-x.net/auth
        realm: CX-Central
        client-id: Cl7-CX-BPDM
        permissions:
          createTask: write_partner
          readTask: write_partner
          reservation:
            clean: write_partner
            cleanAndSync: write_partner
            poolSync: write_partner
          result:
            clean: write_partner
            cleanAndSync: write_partner
            poolSync: write_partner

bpdm-cleaning-service-dummy:
  fullnameOverride: bpdm-int-cleaning-service
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  applicationConfig:
    bpdm:
      client:
        orchestrator:
          base-url: "http://bpdm-int-orchestrator/orchestrator"
          provider:
            issuer-uri: https://centralidp.int.catena-x.net/auth/realms/CX-Central
          registration:
            client-id: <path:bpdm/data/int/bpdm/cleaning-service/orchestrator-client#client-id>
  applicationSecrets:
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret:  <path:bpdm/data/int/bpdm/cleaning-service/orchestrator-client#client-secret>

postgres:
  fullnameOverride: ""
  auth:
    postgresPassword: <path:bpdm/data/int/bpdm/postgresql#postgres-password>
    password: <path:bpdm/data/int/bpdm/postgresql#password>

keycloak:
  enabled: true
  postgresql:
    enabled: true
    nameOverride: "keycloak-postgres"
    auth:
      postgresPassword: <path:bpdm/data/int/bpdm/keycloak/postgresql#postgresql-password>
      username: bn_keycloak
      password: <path:bpdm/data/int/bpdm/keycloak/postgresql#password>
      database: bitnami_keycloak
  auth:
    adminPassword: <path:bpdm/data/int/bpdm/keycloak/admin#admin-password>
  ingress:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    ingressClassName: "nginx"
    hostname: "keycloak-bpdm.int.catena-x.net"
    servicePort: http