bpdm-gate:
  fullnameOverride: bpdm-int-gate-test-company
  ingress:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
      - host: business-partners.int.catena-x.net
        paths:
          - path: "/companies/test-company"
            pathType: Prefix
    tls:
      - secretName: tls-secret-bpdm-gate
        hosts:
          - business-partners.int.catena-x.net
  livenessProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/companies/test-company/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/companies/test-company"
    bpdm:
      bpn:
        owner-bpn-l:
      tasks:
        creation:
          fromSharingMember:
            starts-as-ready: true
      client:
        pool:
          base-url: "http://bpdm-int-pool/pool"
          registration:
            client-id: <path:bpdm/data/int/bpdm/gates/portal/pool-client#client-id>
        orchestrator:
          base-url: "http://bpdm-int-orchestrator/orchestrator"
          registration:
            client-id: <path:bpdm/data/int/bpdm/gates/portal/orchestrator-client#client-id>
      security:
        auth-server-url: https://centralidp.int.catena-x.net/auth
        permissions:
          uploadInputPartner: write_input_partner
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/int/bpdm/postgresql#password>
    bpdm:
      client:
        pool:
          registration:
            client-secret: <path:bpdm/data/int/bpdm/gates/portal/pool-client#client-secret>
        orchestrator:
          registration:
            client-secret: <path:bpdm/data/int/bpdm/gates/portal/orchestrator-client#client-secret>

bpdm-pool:
  fullnameOverride: bpdm-int-pool
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: business-partners.int.catena-x.net
        paths:
          - path: /pool
            pathType: Prefix
    tls:
      - secretName: tls-secret-bpdm-pool
        hosts:
          - business-partners.int.catena-x.net
  livenessProbe:
    httpGet:
      path: "/pool/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/pool/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/pool/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/pool"
    bpdm:
      client:
        orchestrator:
          base-url: "http://bpdm-int-orchestrator/orchestrator"
          registration:
            client-id: <path:bpdm/data/int/bpdm/pool/orchestrator-client#client-id>
      security:
        auth-server-url: https://centralidp.int.catena-x.net/auth
    springdoc:
      swagger-ui:
        oauth:
          client-id: Cl2-CX-Portal
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/int/bpdm/postgresql#password>
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret: <path:bpdm/data/int/bpdm/pool/orchestrator-client#client-secret>

bpdm-orchestrator:
  fullnameOverride: bpdm-int-orchestrator
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: business-partners.int.catena-x.net
        paths:
          - path: /orchestrator
            pathType: Prefix
    tls:
      - secretName: tls-secret-bpdm-orchestrator
        hosts:
          - business-partners.int.catena-x.net
  livenessProbe:
    httpGet:
      path: "orchestrator/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "orchestrator/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "orchestrator/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/orchestrator"
    bpdm:
      security:
        auth-server-url: https://centralidp.int.catena-x.net/auth
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/int/bpdm/postgresql#password>

bpdm-cleaning-service-dummy:
  fullnameOverride: bpdm-int-cleaning-service
  enabled: true
  applicationConfig:
    bpdm:
      client:
        orchestrator:
          base-url: "http://bpdm-int-orchestrator/orchestrator"
          provider:
            issuer-uri: https://centralidp.int.catena-x.net/auth/realms/CX-Central
          registration:
            client-id: <path:bpdm/data/int/bpdm/cleaning-service/orchestrator-client#client-id>
  applicationSecrets:
    bpdm:
      client:
        orchestrator:
          registration:
            client-secret:  <path:bpdm/data/int/bpdm/cleaning-service/orchestrator-client#client-secret>

postgres:
  auth:
    postgresPassword: <path:bpdm/data/int/bpdm/postgresql#postgres-password>
    password: <path:bpdm/data/int/bpdm/postgresql#password>

centralidp:
  enabled: false