image:
  tag: "main"

springProfiles:
  - auth

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: partners-pool-pen.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - partners-pool-pen.dev.demo.catena-x.net

applicationConfig:
  bpdm:
    opensearch:
      export-scheduler-cron-expr: 0 30 * * * *
    security:
      auth-server-url: https://centralidp-pen.dev.demo.catena-x.net/auth
      realm: CX-Central
      client-id: Cl7-CX-BPDM
  springdoc:
    swagger-ui:
      oauth:
        client-id: Cl2-CX-Portal

applicationSecrets:
  spring:
    datasource:
      password: <path:bpdm/data/pen-dev/pool/postgresql#password>


postgres:
  auth:
    postgresPassword: <path:bpdm/data/pen-dev/pool/postgresql#postgres-password>
    password: <path:bpdm/data/pen-dev/pool/postgresql#password>
