bpdm-gate:
  fullnameOverride: bpdm-int-gate-portal
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 2Gi
  springProfiles:
    - auth
    - pool-auth
  ingress:
    enabled: true
    hosts:
      - host: business-partners.int.demo.catena-x.net
        paths:
          - path: "/companies/portal/gate"
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - business-partners.int.demo.catena-x.net
  livenessProbe:
    httpGet:
      path: "/companies/portal/gate/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/companies/portal/gate/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/companies/portal/gate/actuator/health/readiness"
  applicationConfig:
    server:
      servlet:
        context-path: "/companies/portal/gate"
    bpdm:
      gate-security:
        readCompanyInputData: view_company_data
        changeCompanyInputData: change_company_data
        readCompanyOutputData: view_shared_data
        changeCompanyOutputData: change_company_data
      security:
        auth-server-url: https://centralidp.int.demo.catena-x.net/auth
        realm: CX-Central
        client-id: Cl16-CX-BPDMGate-Portal
    springdoc:
      swagger-ui:
        oauth:
          client-id: Cl2-CX-Portal
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/int/companies/portal/postgresql#password>
  postgres:
    enabled: false

bpdm-pool:
  enabled: false

bpdm-bridge-dummy:
  fullnameOverride: bpdm-int-bridge-portal
  springProfiles:
    - auth
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: business-partners.int.demo.catena-x.net
        paths:
          - path: /companies/portal/bridge
            pathType: Prefix
    tls:
      - secretName: tls-secret
        hosts:
          - business-partners.int.demo.catena-x.net
  livenessProbe:
    httpGet:
      path: "/companies/portal/bridge/actuator/health/liveness"
  readinessProbe:
    httpGet:
      path: "/companies/portal/bridge/actuator/health/readiness"
  startupProbe:
    httpGet:
      path: "/companies/portal/bridge/actuator/health/readiness"
  resources:
    limits:
      cpu: 800m
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 2Gi
  applicationConfig:
    server:
      servlet:
        context-path: "/companies/portal/bridge"
    bpdm:
      bridge:
        syncAuthorities: add_company_data
      pool:
        base-url: "http://bpdm-int-pool:8080/pool"
        oauth2-client-registration: bridge-pool-client
      gate:
        base-url: "http://bpdm-int-gate-portal:8080/companies/portal/gate"
        oauth2-client-registration: bridge-gate-client
      security:
        auth-server-url: https://centralidp.int.demo.catena-x.net/auth
        realm: CX-Central
        client-id: Cl7-CX-BPDM
    spring:
      security:
        oauth2:
          client:
            registration:
              bridge-pool-client:
                # Client ID used for getting token different from own Client to validate tokens
                client-id: sa-cl7-cx-7
                authorization-grant-type: client_credentials
                provider: catena-keycloak-provider
              bridge-gate-client:
                # Client ID used for getting token different from own Client to validate tokens
                client-id: sa-cl7-cx-7
                authorization-grant-type: client_credentials
                provider: catena-keycloak-provider
            provider:
              catena-keycloak-provider:
                issuer-uri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central
  applicationSecrets:
    spring:
      datasource:
        password: <path:bpdm/data/int/companies/portal/postgresql#password>
      security:
        oauth2:
          client:
            registration:
              bridge-pool-client:
                client-secret: <path:bpdm/data/int/companies/portal/bridge#pool-client-secret>
              bridge-gate-client:
                client-secret: <path:bpdm/data/int/companies/portal/bridge#gate-client-secret>


postgres:
  auth:
    postgresPassword: <path:bpdm/data/int/companies/portal/postgresql#postgres-password>
    password: <path:bpdm/data/int/companies/portal/postgresql#password>

opensearch:
  enabled: false